# yaml-language-server: $schema=../../../.fluence/schemas/service.json

# Defines a [Marine service](https://fluence.dev/docs/build/concepts/#services), most importantly the modules that the service consists of. You can use `fluence service new` command to generate a template for new service

# Documentation: https://github.com/fluencelabs/cli/tree/main/docs/configs/service.md

version: 0

name: myRPC

modules:
  facade:
    get: modules/myRPC
  curl_effector:
    get: https://github.com/fluencelabs/curl-effector/releases/download/effector-v0.1.1/curl_effector.tar.gz
  ipfs_effector:
    get: https://github.com/fluencelabs/ipfs-effector/releases/download/effector-v0.1.1/ipfs_effector.tar.gz
